Code Review HW10
Stevens-SSE/wordle-group-d pull request #2
Opened 2022-04-08 00:39 UTC by aishwaryashirbhate

Hello Aakash and Jefferson, please review the HW10 code.

2022-04-11 02:44 UTC, jeffft9 requested changes
Hello Aishwarya, 
Please review the comments and perform the necessary code changes.

Thanks,
Jefferson

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_Wordle_Solver.py
> +    def find_words(self, clue, guess):
Please add comments for the function for better understanding.
No type hints provided.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_Wordle_helper.py
> +
Please add comments before function to explain the purpose of function, for better understanding.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_dictionary_final.py
> +
Well written code and comments. No change required.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_Wordle_helper.py
> +        print("Please enter good letters")
No type hints provided.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_Wordle_helper.py
> +        h = List(0)
No type hints provided.
Usage of meaningful variable names is recommended. Example - "head" instead of "h"

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_Wordle_helper.py
> +    def find_words(self, clue, guess):
No type hints provided.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_occurence_stats_final.py
> +if __name__ == '__main__':
Nicely written code with comments and type hints. No code change required.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_ui_final.py
> +                    if bool_symbolcheck is False:
Can use python's 'isalpha()' method for checking if word is containing only characters or not. No need to write all special characters and check. Will save lot of code lines and comparisons.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_utility_final.py
> +
No changes required. Well done.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_wordle_final.py
> +
No changes required. Well done

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_Wordle_helper.py
> +            reader = csv.DictReader(csvfile.readlines()[0:n])
Please explain usage of itemgetter and why it was required(in comments), since anyone who doesn't know itemgetter might not understand it.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Wordle_Test_final.py
> +
Well done. Plenty of test cases covered.

2022-04-11 02:44 UTC, jeffft9 commented on HW10_Aishwarya_Shirbhate_occurence_stats_final.py
> +            print("Error:", sys.exc_info()[0], "in Parse_file_to_tuple function")
wordlist not closed(file not closed). Ensure file is closed before function end.

2022-04-13 09:03 UTC, TheAakash1886 commented on HW10_Aishwarya_Shirbhate_occurence_stats_final.py
> +            for i in range(97, 123):  # taking  ASCII values of alphabets
Great job with the comments making it clear why this range is used.

2022-04-13 09:05 UTC, TheAakash1886 commented on HW10_Aishwarya_Shirbhate_Wordle_Solver.py
> +        return r
The variable could be named better and/or comments could be added to better convey what is being returned.

2022-04-13 09:08 UTC, TheAakash1886 commented on HW10_Aishwarya_Shirbhate_Wordle_helper.py
> +        t = h
Variable names could be more descriptive like the example provided by my colleague above being "head" instead of "h".

2022-04-13 09:22 UTC, TheAakash1886 commented on HW10_Aishwarya_Shirbhate_wordle_final.py
> +
Nice and clean code with descriptive comments. Great

2022-04-13 09:23 UTC, TheAakash1886 commented on HW10_Aishwarya_Shirbhate_ui_final.py
> +            get_columns = itemgetter('rank', 'words')
Could do with a comment of why this is being done as it may not be immediately apparent.

2022-04-13 09:26 UTC, TheAakash1886 commented on HW10_Aishwarya_Shirbhate_occurence_stats_final.py
> +                write_obj.truncate(0)
Can be made clear with the use of comments of why this is used.

2022-04-18 16:24 UTC, aishwaryashirbhate commented
code changes done as per review comments

2022-04-18 16:24 UTC, merged